### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by cosoc** [Taptiive/machineid-rs#3]
Support for mac？

**Comment by Taptiive** [comment]
These are the components that are not available for mac:

- SystemID
- MacAddress
- DriveSerial

I will try to add support for those components in the next versions ;)

**Comment by riadloukili** [comment]
Any update on this?

**Comment by Taptiive** [comment]
Hey, i merged the pull request and now the crate supports MacOS. Thanks for the suggestions!
